version: '3'

services:
  frontend:
    image: qdrant-ui
    build:
      context: .
    environment:
      - REACT_APP_API_URL=http://localhost:6333
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: qdrant/qdrant
    ports:
      - '6333:6333'
