version: '3'

services:
  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    image: qdrant-ui
    build:
      dockerfile: Dockerfile.prod
    environment:
      - REACT_APP_API_URL=http://localhost:6333
    ports:
      - '3000:3000'
    volumes:
      - my_volume:/app
    depends_on:
      - db
  db:
    extends:
      file: docker-compose.yml
      service: db
volumes:
  my_volume:
