version: '3'

services:
  frontend:
    image: qdrant-ui
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - REACT_APP_API_URL=http://localhost:6333
    ports:
      - '3000:3000'
    volumes:
      - my_volume:/app
    depends_on:
      - db
volumes:
  my_volume:
